    name: Deploy MultiDocker
    on:
      push:
        branches:
          - main
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t jchoponis/react-test -f ./client/dockerfile.dev ./client
          - run: docker run -e CI=true jchoponis/react-test npm test
     
          - run: docker build -t jchoponis/multi-client ./client
          - run: docker build -t jchoponis/multi-nginx ./nginx
          - run: docker build -t jchoponis/multi-server ./server
          - run: docker build -t jchoponis/multi-worker ./worker
     
          - run: docker push jchoponis/multi-client
          - run: docker push jchoponis/multi-nginx
          - run: docker push jchoponis/multi-server
          - run: docker push jchoponis/multi-worker
     
          # - name: Generate deployment package
          #   run: zip -r deploy.zip . -x '*.git*'
     
          # - name: Deploy to EB
          #   uses: einaregilsson/beanstalk-deploy@v18
          #   with:
          #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          #     application_name: docker-react-1
          #     environment_name: Dockerreact1-env-1
          #     existing_bucket_name: elasticbeanstalk-us-east-1-879577878990
          #     region: us-east-1
          #     version_label: ${{ github.sha }}
          #     deployment_package: deploy.zip